### ISSUE TITLE
Set up API client and authentication

### ISSUE THREAD

**Issue by iamEAP** [run-crank/cog-pardot#1]
## Problem / motivation
Naturally, we will not be able to achieve much without the ability to authenticate with Pardot.

## Scope / UAT Target
- [x] Client Wrapper should wrap an API client that uses `v4` of the Pardot API.
- [x] User should be able to authenticate with the following details:
  - [x] Email address - email address of user account
  - [x] Password - password of user account
  - [x] User Key - 32 character hexadecimal user key for user account
- [x] Error handling (in ClientWrapper constructor, and generally available to steps)
  - [x] Should immediately return an error on failed authentication attempt (`error code 15`), using an appropriate error message
  - [x] Should immediately return an error when daily API limit is reached (`error code 122`), using an appropriate error message (e.g. `API call limit reached for today.`)
  - [x] Should implement retry logic when `error code 66` (max concurrent requests reached), up to a a time limit of perhaps 60 seconds.

## Proposed Resolution
This fork of an existing Pardot API client for v3 looks reasonable for v4: https://www.npmjs.com/package/lew-pardot

## Resources
- [API Authentication & Rate Limits](http://developer.pardot.com/#authentication)

**Comment by amcpanaligan** [comment]
@iamEAP hello, do we have any creds set up for this?

**Comment by amcpanaligan** [comment]
> @iamEAP hello, do we have any creds set up for this?

I am checking the wiki

**Comment by amcpanaligan** [comment]
Ok. Seen it! Thanks

**Comment by amcpanaligan** [comment]
@iamEAP It seems the library does not expose the error_codes on auth error

**Comment by iamEAP** [comment]
Ah-hah.  It looks to be translating error codes (maybe somewhat annoyingly) into human-readable codes here: https://github.com/lewsegadilha/lew-pardot/blob/master/lib/errors.js

Also unfortunately, the underlying library uses a very old promise library ([Q Promise](https://github.com/kriskowal/q)), which does not conform at all to the native promise spec.

So we won't be able to `async/await` any of these, unless we manually wrap calls to the pardot client with something like...

```typescript
return new Promise((resolve, reject) => {
  this.client.prospects.create(args)
    .then(resolve)
    .fail(reject); // Note Q's non-standard .fail() instead of .catch()
});
```

**Comment by iamEAP** [comment]
It's possible that you're not getting an error/error code because it's using an un-mapped error code.

Here's a PR on the original repo that adds a bunch of error codes: https://github.com/micahlmartin/pardot/pull/2/files

Which do not appear in the fork we're using: https://github.com/lewsegadilha/lew-pardot/blob/master/lib/errors.js

**Comment by iamEAP** [comment]
@amcpanaligan how about we try using our own fork...

I created one that merges in changes from the three open PRs against the original repo + security fixes, 

```shell-session
$ npm uninstall lew-pardot
$ npm install --save git://github.com/iamEAP/lew-pardot#240769ed
```

Full changeset viewable here: https://github.com/lewsegadilha/lew-pardot/compare/master...iamEAP:apply-existing-patches

**Comment by amcpanaligan** [comment]
Sugoi~!

**Comment by amcpanaligan** [comment]
@iamEAP The `error code`s are still not exposed. Only a generic `LOGIN FAILED` gets returned.
